<!-- wp:uagb/container {"block_id":"77ef3999","backgroundType":"image","backgroundImageDesktop":{"id":944,"title":"moutain-bike","filename":"moutain-bike.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/moutain-bike.jpg","link":"https://shop.bradthompsonweb.dev/moutain-bike/","alt":"","author":"39","description":"","caption":"","name":"moutain-bike","status":"inherit","uploadedTo":0,"date":"2021-04-02T12:52:42.000Z","modified":"2021-04-02T12:52:42.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 2, 2021","nonces":{"update":"6c1d10d0ee","delete":"76d776efb1","edit":"1116ecdf21"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=944\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":288169,"filesizeHumanReadable":"281 KB","context":"","height":1080,"width":1920,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/moutain-bike-150x150.jpg","orientation":"landscape"},"medium":{"height":169,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/moutain-bike-300x169.jpg","orientation":"landscape"},"large":{"height":576,"width":1024,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/moutain-bike-1024x576.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/moutain-bike.jpg","height":1080,"width":1920,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.38) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":200,"bottomPaddingDesktop":120,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":130,"bottomPaddingTablet":80,"leftPaddingTablet":30,"rightPaddingTablet":30,"topPaddingMobile":130,"bottomPaddingMobile":80,"leftPaddingMobile":30,"rightPaddingMobile":30,"paddingLink":false,"variationSelected":true,"isBlockRootParent":true,"overlayType":"gradient"} -->
<div class="wp-block-uagb-container uagb-block-77ef3999 alignfull uagb-is-root-container">
    <div class="uagb-container-inner-blocks-wrap">
        <!-- wp:uagb/advanced-heading {"block_id":"a0dfcabf","classMigrate":true,"headingAlign":"center","headingColor":"var(\u002d\u002dast-global-color-5)","headingTag":"h1","headSpace":0} -->
        <div class="wp-block-uagb-advanced-heading uagb-block-a0dfcabf">
            <h1 class="uagb-heading-text">VINTAGE VINYL​</h1>
        </div>
        <!-- /wp:uagb/advanced-heading -->
    </div>
</div>
<!-- /wp:uagb/container -->

<!-- wp:uagb/container {"block_id":"6b97439c","backgroundType":"color","backgroundSizeTablet":"cover","backgroundSizeMobile":"cover","backgroundColor":"var(\u002d\u002dast-global-color-5)","topPaddingDesktop":120,"bottomPaddingDesktop":0,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":80,"bottomPaddingTablet":0,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":80,"bottomPaddingMobile":0,"leftPaddingMobile":20,"rightPaddingMobile":20,"paddingLink":false,"variationSelected":true,"isBlockRootParent":true} -->
<div class="wp-block-uagb-container uagb-block-6b97439c alignfull uagb-is-root-container">
    <div class="uagb-container-inner-blocks-wrap">
        <!-- wp:uagb/advanced-heading {"block_id":"93a9a65d","classMigrate":true} -->
        <div class="wp-block-uagb-advanced-heading uagb-block-93a9a65d">
            <h2 class="uagb-heading-text">OUR STORY</h2>
        </div>
        <!-- /wp:uagb/advanced-heading -->
    </div>
</div>
<!-- /wp:uagb/container -->

<!-- wp:uagb/container {"block_id":"abde13d9","directionDesktop":"row","alignItemsDesktop":"stretch","alignItemsTablet":"flex-start","backgroundType":"color","backgroundSizeTablet":"cover","backgroundSizeMobile":"cover","backgroundColor":"var(\u002d\u002dast-global-color-5)","topPaddingDesktop":40,"bottomPaddingDesktop":0,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":30,"bottomPaddingTablet":0,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":30,"bottomPaddingMobile":0,"leftPaddingMobile":20,"rightPaddingMobile":20,"paddingLink":false,"variationSelected":true,"rowGapMobile":0,"columnGapTablet":0,"isBlockRootParent":true,"equalHeight":true} -->
<div class="wp-block-uagb-container uagb-block-abde13d9 alignfull uagb-is-root-container">
    <div class="uagb-container-inner-blocks-wrap">
        <!-- wp:uagb/container {"block_id":"38f17470","widthDesktop":33,"alignItemsDesktop":"stretch","topPaddingDesktop":0,"bottomPaddingDesktop":0,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"topMarginTablet":10,"bottomMarginTablet":10,"leftMarginTablet":10,"rightMarginTablet":10,"topMarginMobile":10,"bottomMarginMobile":10,"leftMarginMobile":10,"rightMarginMobile":10,"variationSelected":true,"rowGapDesktop":0,"rowGapTablet":20,"rowGapMobile":20,"widthSetByUser":true,"equalHeight":true} -->
        <div class="wp-block-uagb-container uagb-block-38f17470">
            <!-- wp:uagb/container {"block_id":"5da8b31b","backgroundType":"image","backgroundImageDesktop":{"id":1030,"title":"2002","filename":"2002.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2002.jpg","link":"https://shop.bradthompsonweb.dev/2002/","alt":"","author":"39","description":"","caption":"","name":"2002","status":"inherit","uploadedTo":0,"date":"2021-04-05T06:12:14.000Z","modified":"2021-04-05T06:12:14.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 5, 2021","nonces":{"update":"e8848872ae","delete":"7a63ba8854","edit":"44b95ee0b0"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=1030\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":99737,"filesizeHumanReadable":"97 KB","context":"","height":500,"width":700,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2002-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2002-300x214.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2002.jpg","height":500,"width":700,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":35,"bottomPaddingDesktop":35,"leftPaddingDesktop":35,"rightPaddingDesktop":40,"topPaddingTablet":35,"bottomPaddingTablet":35,"leftPaddingTablet":35,"rightPaddingTablet":40,"topPaddingMobile":35,"bottomPaddingMobile":35,"leftPaddingMobile":35,"rightPaddingMobile":40,"paddingLink":false,"topMarginDesktop":10,"bottomMarginDesktop":10,"leftMarginDesktop":10,"rightMarginDesktop":10,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginMobile":0,"bottomMarginMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"variationSelected":true,"widthSetByUser":true,"overlayType":"gradient"} -->
            <div class="wp-block-uagb-container uagb-block-5da8b31b">
                <!-- wp:uagb/advanced-heading {"block_id":"d57022b1","classMigrate":true,"headingDescToggle":true,"headingColor":"var(\u002d\u002dast-global-color-5)","subHeadingColor":"var(\u002d\u002dast-global-color-0)","headingTag":"h5","headSpace":0,"subHeadFontFamily":"Racing Sans One","subHeadFontWeight":"400","subHeadFontSize":18,"subHeadFontSizeTablet":16,"subHeadLoadGoogleFonts":true,"blockTopPadding":30,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingUnit":"%","blockPaddingLink":true} -->
                <div class="wp-block-uagb-advanced-heading uagb-block-d57022b1">
                    <h5 class="uagb-heading-text">FIRST STORE​</h5>
                    <p class="uagb-desc-text">2012​</p>
                </div>
                <!-- /wp:uagb/advanced-heading -->
            </div>
            <!-- /wp:uagb/container -->

            <!-- wp:uagb/container {"block_id":"1f9c8e16","backgroundType":"image","backgroundImageDesktop":{"id":1033,"title":"2004","filename":"2004-2.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2004-2.jpg","link":"https://shop.bradthompsonweb.dev/2004-3/","alt":"","author":"39","description":"","caption":"","name":"2004-3","status":"inherit","uploadedTo":0,"date":"2021-04-05T06:22:47.000Z","modified":"2021-04-05T06:22:47.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 5, 2021","nonces":{"update":"67155c3b01","delete":"fc222248f2","edit":"aa893864cc"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=1033\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":130673,"filesizeHumanReadable":"128 KB","context":"","height":500,"width":700,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2004-2-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2004-2-300x214.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2004-2.jpg","height":500,"width":700,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":35,"bottomPaddingDesktop":35,"leftPaddingDesktop":35,"rightPaddingDesktop":40,"topPaddingTablet":35,"bottomPaddingTablet":35,"leftPaddingTablet":35,"rightPaddingTablet":40,"topPaddingMobile":35,"bottomPaddingMobile":35,"leftPaddingMobile":35,"rightPaddingMobile":40,"paddingLink":false,"topMarginDesktop":10,"bottomMarginDesktop":10,"leftMarginDesktop":10,"rightMarginDesktop":10,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginMobile":0,"bottomMarginMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"variationSelected":true,"widthSetByUser":true,"overlayType":"gradient"} -->
            <div class="wp-block-uagb-container uagb-block-1f9c8e16">
                <!-- wp:uagb/advanced-heading {"block_id":"fb067de3","classMigrate":true,"headingDescToggle":true,"headingColor":"var(\u002d\u002dast-global-color-5)","subHeadingColor":"var(\u002d\u002dast-global-color-0)","headingTag":"h5","headSpace":0,"subHeadFontFamily":"Racing Sans One","subHeadFontWeight":"400","subHeadFontSize":18,"subHeadFontSizeTablet":16,"subHeadLoadGoogleFonts":true,"blockTopPadding":30,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingUnit":"%"} -->
                <div class="wp-block-uagb-advanced-heading uagb-block-fb067de3">
                    <h5 class="uagb-heading-text">WEBSITE LAUNCH​</h5>
                    <p class="uagb-desc-text">2014</p>
                </div>
                <!-- /wp:uagb/advanced-heading -->
            </div>
            <!-- /wp:uagb/container -->
        </div>
        <!-- /wp:uagb/container -->

        <!-- wp:uagb/container {"block_id":"e41be8e6","widthDesktop":66,"justifyContentDesktop":"flex-end","backgroundType":"image","backgroundImageDesktop":{"id":1034,"title":"2005","filename":"2005.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2005.jpg","link":"https://shop.bradthompsonweb.dev/2005/","alt":"","author":"39","description":"","caption":"","name":"2005","status":"inherit","uploadedTo":0,"date":"2021-04-05T06:22:48.000Z","modified":"2021-04-05T06:22:48.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 5, 2021","nonces":{"update":"836dce3f6f","delete":"ebc89f389f","edit":"bd9829a245"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=1034\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":84091,"filesizeHumanReadable":"82 KB","context":"","height":500,"width":700,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2005-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2005-300x214.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2005.jpg","height":500,"width":700,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":35,"bottomPaddingDesktop":35,"leftPaddingDesktop":35,"rightPaddingDesktop":40,"topPaddingTablet":35,"bottomPaddingTablet":35,"leftPaddingTablet":35,"rightPaddingTablet":40,"topPaddingMobile":35,"bottomPaddingMobile":35,"leftPaddingMobile":35,"rightPaddingMobile":40,"paddingLink":false,"topMarginDesktop":10,"bottomMarginDesktop":10,"leftMarginDesktop":10,"rightMarginDesktop":10,"topMarginMobile":10,"bottomMarginMobile":10,"leftMarginMobile":10,"rightMarginMobile":10,"variationSelected":true,"widthSetByUser":true,"overlayType":"gradient"} -->
        <div class="wp-block-uagb-container uagb-block-e41be8e6">
            <!-- wp:uagb/advanced-heading {"block_id":"a3281c57","classMigrate":true,"headingDescToggle":true,"headingColor":"var(\u002d\u002dast-global-color-5)","subHeadingColor":"var(\u002d\u002dast-global-color-0)","headingTag":"h4","headSpace":0,"subHeadFontFamily":"Racing Sans One","subHeadFontWeight":"400","subHeadFontSize":22,"subHeadFontSizeTablet":20,"subHeadLoadGoogleFonts":true,"blockTopPadding":30,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingUnit":"%"} -->
            <div class="wp-block-uagb-advanced-heading uagb-block-a3281c57">
                <h4 class="uagb-heading-text">SECOND STORE</h4>
                <p class="uagb-desc-text">2015</p>
            </div>
            <!-- /wp:uagb/advanced-heading -->
        </div>
        <!-- /wp:uagb/container -->
    </div>
</div>
<!-- /wp:uagb/container -->

<!-- wp:uagb/container {"block_id":"9d62c882","directionDesktop":"row","alignItemsDesktop":"stretch","alignItemsTablet":"flex-start","backgroundType":"color","backgroundSizeTablet":"cover","backgroundSizeMobile":"cover","backgroundColor":"var(\u002d\u002dast-global-color-5)","topPaddingDesktop":0,"bottomPaddingDesktop":120,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":0,"bottomPaddingTablet":70,"leftPaddingTablet":20,"rightPaddingTablet":20,"topPaddingMobile":0,"bottomPaddingMobile":70,"leftPaddingMobile":20,"rightPaddingMobile":20,"paddingLink":false,"variationSelected":true,"rowGapMobile":0,"columnGapDesktop":0,"isBlockRootParent":true,"equalHeight":true} -->
<div class="wp-block-uagb-container uagb-block-9d62c882 alignfull uagb-is-root-container">
    <div class="uagb-container-inner-blocks-wrap">
        <!-- wp:uagb/container {"block_id":"a623149f","widthDesktop":66,"justifyContentDesktop":"flex-end","backgroundType":"image","backgroundImageDesktop":{"id":1035,"title":"2005-2","filename":"2005-2.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2005-2.jpg","link":"https://shop.bradthompsonweb.dev/2005-2/","alt":"","author":"39","description":"","caption":"","name":"2005-2","status":"inherit","uploadedTo":0,"date":"2021-04-05T06:26:39.000Z","modified":"2021-04-05T06:26:39.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 5, 2021","nonces":{"update":"1e0eeb9f17","delete":"bc3351da95","edit":"828d61e5da"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=1035\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":135964,"filesizeHumanReadable":"133 KB","context":"","height":500,"width":700,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2005-2-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2005-2-300x214.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2005-2.jpg","height":500,"width":700,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":35,"bottomPaddingDesktop":35,"leftPaddingDesktop":35,"rightPaddingDesktop":40,"topPaddingTablet":35,"bottomPaddingTablet":35,"leftPaddingTablet":35,"rightPaddingTablet":40,"topPaddingMobile":35,"bottomPaddingMobile":35,"leftPaddingMobile":35,"rightPaddingMobile":40,"paddingLink":false,"topMarginDesktop":10,"bottomMarginDesktop":10,"leftMarginDesktop":10,"rightMarginDesktop":10,"topMarginMobile":10,"bottomMarginMobile":10,"leftMarginMobile":10,"rightMarginMobile":10,"variationSelected":true,"widthSetByUser":true,"overlayType":"gradient"} -->
        <div class="wp-block-uagb-container uagb-block-a623149f">
            <!-- wp:uagb/advanced-heading {"block_id":"28dfd496","classMigrate":true,"headingDescToggle":true,"headingColor":"var(\u002d\u002dast-global-color-5)","subHeadingColor":"var(\u002d\u002dast-global-color-0)","headingTag":"h4","headSpace":0,"subHeadFontFamily":"Racing Sans One","subHeadFontWeight":"400","subHeadFontSize":22,"subHeadFontSizeTablet":20,"subHeadLoadGoogleFonts":true,"blockTopPadding":30,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingUnit":"%"} -->
            <div class="wp-block-uagb-advanced-heading uagb-block-28dfd496">
                <h4 class="uagb-heading-text">#ALBUMOFTHEMONTH CLUB​</h4>
                <p class="uagb-desc-text">2016</p>
            </div>
            <!-- /wp:uagb/advanced-heading -->
        </div>
        <!-- /wp:uagb/container -->

        <!-- wp:uagb/container {"block_id":"69380490","widthDesktop":33,"alignItemsDesktop":"stretch","justifyContentTablet":"flex-start","topPaddingDesktop":0,"bottomPaddingDesktop":0,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":0,"bottomPaddingTablet":0,"leftPaddingTablet":0,"rightPaddingTablet":0,"topPaddingMobile":0,"bottomPaddingMobile":0,"leftPaddingMobile":0,"rightPaddingMobile":0,"topMarginTablet":10,"bottomMarginTablet":10,"leftMarginTablet":10,"rightMarginTablet":10,"topMarginMobile":10,"bottomMarginMobile":10,"leftMarginMobile":10,"rightMarginMobile":10,"variationSelected":true,"rowGapDesktop":0,"rowGapTablet":20,"rowGapMobile":20,"widthSetByUser":true,"equalHeight":true} -->
        <div class="wp-block-uagb-container uagb-block-69380490">
            <!-- wp:uagb/container {"block_id":"e09dabc7","backgroundType":"image","backgroundImageDesktop":{"id":1036,"title":"2008","filename":"2008.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2008.jpg","link":"https://shop.bradthompsonweb.dev/2008/","alt":"","author":"39","description":"","caption":"","name":"2008","status":"inherit","uploadedTo":0,"date":"2021-04-05T06:28:57.000Z","modified":"2021-04-05T06:28:57.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 5, 2021","nonces":{"update":"8c2d7e2371","delete":"59dd45baa3","edit":"dbb70eedd5"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=1036\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":72511,"filesizeHumanReadable":"71 KB","context":"","height":500,"width":700,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2008-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/2008-300x214.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/2008.jpg","height":500,"width":700,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":35,"bottomPaddingDesktop":35,"leftPaddingDesktop":35,"rightPaddingDesktop":40,"topPaddingTablet":35,"bottomPaddingTablet":35,"leftPaddingTablet":35,"rightPaddingTablet":40,"topPaddingMobile":35,"bottomPaddingMobile":35,"leftPaddingMobile":35,"rightPaddingMobile":40,"paddingLink":false,"topMarginDesktop":10,"bottomMarginDesktop":10,"leftMarginDesktop":10,"rightMarginDesktop":10,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginMobile":0,"bottomMarginMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"variationSelected":true,"widthSetByUser":true,"overlayType":"gradient"} -->
            <div class="wp-block-uagb-container uagb-block-e09dabc7">
                <!-- wp:uagb/advanced-heading {"block_id":"04fd2142","classMigrate":true,"headingDescToggle":true,"headingColor":"var(\u002d\u002dast-global-color-5)","subHeadingColor":"var(\u002d\u002dast-global-color-0)","headingTag":"h5","headSpace":0,"subHeadFontFamily":"Racing Sans One","subHeadFontWeight":"400","subHeadFontSize":18,"subHeadFontSizeTablet":16,"subHeadLoadGoogleFonts":true,"blockTopPadding":30,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingUnit":"%"} -->
                <div class="wp-block-uagb-advanced-heading uagb-block-04fd2142">
                    <h5 class="uagb-heading-text">THIRD STORE</h5>
                    <p class="uagb-desc-text">2017​</p>
                </div>
                <!-- /wp:uagb/advanced-heading -->
            </div>
            <!-- /wp:uagb/container -->

            <!-- wp:uagb/container {"block_id":"f530609d","backgroundType":"image","backgroundImageDesktop":{"id":1037,"title":"today","filename":"today.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/today.jpg","link":"https://shop.bradthompsonweb.dev/today/","alt":"","author":"39","description":"","caption":"","name":"today","status":"inherit","uploadedTo":0,"date":"2021-04-05T06:36:00.000Z","modified":"2021-04-05T06:36:00.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"April 5, 2021","nonces":{"update":"ae384ff2d3","delete":"ef87dbd42c","edit":"76d7d367e7"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=1037\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":135391,"filesizeHumanReadable":"132 KB","context":"","height":500,"width":700,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/today-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/04/today-300x214.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/04/today.jpg","height":500,"width":700,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.45) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":35,"bottomPaddingDesktop":35,"leftPaddingDesktop":35,"rightPaddingDesktop":40,"topPaddingTablet":35,"bottomPaddingTablet":35,"leftPaddingTablet":35,"rightPaddingTablet":40,"topPaddingMobile":35,"bottomPaddingMobile":35,"leftPaddingMobile":35,"rightPaddingMobile":40,"paddingLink":false,"topMarginDesktop":10,"bottomMarginDesktop":10,"leftMarginDesktop":10,"rightMarginDesktop":10,"topMarginTablet":0,"bottomMarginTablet":0,"leftMarginTablet":0,"rightMarginTablet":0,"topMarginMobile":0,"bottomMarginMobile":0,"leftMarginMobile":0,"rightMarginMobile":0,"variationSelected":true,"widthSetByUser":true,"overlayType":"gradient"} -->
            <div class="wp-block-uagb-container uagb-block-f530609d">
                <!-- wp:uagb/advanced-heading {"block_id":"670cfd2d","classMigrate":true,"headingDescToggle":true,"headingColor":"var(\u002d\u002dast-global-color-5)","subHeadingColor":"var(\u002d\u002dast-global-color-0)","headingTag":"h5","headSpace":0,"subHeadFontFamily":"Racing Sans One","subHeadFontWeight":"400","subHeadTransform":"capitalize","subHeadFontSize":18,"subHeadFontSizeTablet":16,"subHeadLoadGoogleFonts":true,"blockTopPadding":30,"blockRightPadding":0,"blockLeftPadding":0,"blockBottomPadding":0,"blockPaddingUnit":"%"} -->
                <div class="wp-block-uagb-advanced-heading uagb-block-670cfd2d">
                    <h5 class="uagb-heading-text">AUTHORIZED DEALER</h5>
                    <p class="uagb-desc-text">Today</p>
                </div>
                <!-- /wp:uagb/advanced-heading -->
            </div>
            <!-- /wp:uagb/container -->
        </div>
        <!-- /wp:uagb/container -->
    </div>
</div>
<!-- /wp:uagb/container -->



<!-- wp:uagb/container {"block_id":"1f802f43","innerContentCustomWidthDesktop":900,"backgroundType":"image","backgroundImageDesktop":{"id":738,"title":"bike-hero","filename":"bike-hero.jpg","url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/03/bike-hero.jpg","link":"https://shop.bradthompsonweb.dev/bike-hero/","alt":"","author":"39","description":"","caption":"","name":"bike-hero","status":"inherit","uploadedTo":0,"date":"2021-03-25T10:39:16.000Z","modified":"2021-03-25T10:39:16.000Z","menuOrder":0,"mime":"image/jpeg","type":"image","subtype":"jpeg","icon":"https://shop.bradthompsonweb.dev/wp-content/uploads/2023/10/default.png","dateFormatted":"March 25, 2021","nonces":{"update":"42cf5ebf05","delete":"e0d2400261","edit":"664d2a6683"},"editLink":"https://shop.bradthompsonweb.dev/wp-admin/post.php?post=738\u0026amp;action=edit","meta":false,"authorName":"sonalib","authorLink":"https://shop.bradthompsonweb.dev/wp-admin/user-edit.php?user_id=39","filesizeInBytes":192214,"filesizeHumanReadable":"188 KB","context":"","height":1714,"width":2400,"orientation":"landscape","sizes":{"thumbnail":{"height":150,"width":150,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/03/bike-hero-150x150.jpg","orientation":"landscape"},"medium":{"height":214,"width":300,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/03/bike-hero-300x214.jpg","orientation":"landscape"},"large":{"height":731,"width":1024,"url":"https://websitedemos.net/cycle-shop-08/wp-content/uploads/sites/1016/2021/03/bike-hero-1024x731.jpg","orientation":"landscape"},"full":{"url":"https://shop.bradthompsonweb.dev/wp-content/uploads/2021/03/bike-hero.jpg","height":1714,"width":2400,"orientation":"landscape"}},"compat":{"item":"","meta":""}},"backgroundAttachmentDesktop":"fixed","gradientValue":"linear-gradient(180deg,rgba(0,0,0,0.23) 0%,rgb(22,22,22) 100%)","topPaddingDesktop":200,"bottomPaddingDesktop":200,"leftPaddingDesktop":0,"rightPaddingDesktop":0,"topPaddingTablet":70,"bottomPaddingTablet":70,"leftPaddingTablet":30,"rightPaddingTablet":30,"topPaddingMobile":70,"bottomPaddingMobile":70,"leftPaddingMobile":30,"rightPaddingMobile":30,"paddingLink":false,"variationSelected":true,"isBlockRootParent":true,"overlayType":"gradient"} --><!-- /wp:uagb/container -->